### ISSUE TITLE
한글 자연어 텍스트 분석을 위한 환경 구성, 참고 자료

### ISSUE THREAD

**Issue by GzuPark** [GzuPark/naver-ai-hackathon-2018#1]

**Comment by GzuPark** [comment]
# Env

### TODO  `80%`

- [x] docker 환경으로 setup 
  * `ubuntu 16.04`
  * `python3`, `python-pip`, `python3-dev`, `g++`, `openjdk-7-jdk`, `curl`,  `python3-tk`
  * `git`, `vim`
- [x] python library
  * `konlpy`, `nltk`, `jupyter notebook`, `tensorflow`, `numpy`, `pandas`, `scikit-learn`, `beautifulsoup4`, `gensim`, `seaborn`
- [x] etc
  * `mecab`, `soynlp`

#### openjdk-7-jdk 설치시 `E: Package 'openjdk-7-jdk' has no installation candidate` 오류 대처법
```
apt-get install -f
add-apt-repository ppa:openjdk-r/ppa  
apt-get update
apt-get install openjdk-7-jdk
```

#### konlpy 설치시 생기는 오류
1. `python3-tk`
2. `Jpype1` package

**Comment by GzuPark** [comment]
# Reference

### Videos
* 김현중, 노가다 없는 텍스트 분석을 위한 한국어 NLP (aka. soynlp), PyCon KR 2017 [[link]](https://youtu.be/dxkbvZmbLWc) [[slide]](https://www.slideshare.net/kimhyunjoonglovit/pycon2017-koreannlp)
* 김현중, 미등록단어 문제 해결을 위한 비지도학습 기반 한국어자연어처리 방법론 및 응용, naver d2 [[link]](https://youtu.be/Vj55zaDvn4Q) [[slide]](https://www.slideshare.net/NaverEngineering/ss-86166926)
* T아카데미, 토크ON세미나 3차 자연어처리, SKtechx [[link]](https://www.youtube.com/watch?v=jlCerj5eI4c&list=PL9mhQYIlKEhe_v93zGYsyn0nHE4d2KWqM)
* T아카데미, 토크ON세미나 딥러닝을 활용한 자연어처리 기술 실습, SKtechx [[link]](https://www.youtube.com/watch?v=F8b0jGyZ_W8&list=PL9mhQYIlKEhdorgRaoASuZfgIQTakIEE9)
* [NLP] IMDB 영화리뷰 감정 분석, 오늘코드 [[link]](https://www.youtube.com/watch?v=5D9742ID4XI&list=PLaTc2c6yEwmocBySMhvBttyAD8eZelFIP) [[tutorial]](https://github.com/corazzon/KaggleStruggle/tree/master/word2vec-nlp-tutorial)
* Applied Text Mining in Python, Semantic Text Similarity, Coursera [[link]](https://www.coursera.org/learn/python-text-mining/lecture/DpNWl/semantic-text-similarity)

### Documents
* konlpy [[link]](http://konlpy.org/ko/latest/) *GitHub*
* soynlp [[link]](https://github.com/lovit/soynlp) *GitHub*
* customized_konlpy [[link]](https://github.com/lovit/customized_konlpy) *GitHub*
* Find semantic similarity between two short sentences [[link]](https://stackoverflow.com/questions/44967009/recent-methods-for-finding-semantic-similarity-between-two-short-sentences-or-ar)  *stackoverflow*
* NLP/Machine Learning text comparison [[link]](https://stackoverflow.com/questions/18439795/nlp-machine-learning-text-comparison) *stackoverflow*
* Cosine similarity for vector space models (Part 3) [[link]](http://blog.christianperone.com/2013/09/machine-learning-cosine-similarity-for-vector-space-models-part-iii/) *blog*
* Deep Learning for Semantic Similarity [[link]](https://cs224d.stanford.edu/reports/SanbornAdrian.pdf) *pdf*
* Multi-Perspective Sentence Similarity Modeling with Convolutional Neural Networks [[link]](http://ttic.uchicago.edu/~kgimpel/papers/he+etal.emnlp15.pdf) *pdf*
* Text Similarity Measurement using Convolutional Neural Networks [[link]](https://github.com/hohoCode/textSimilarityConvNet) *GitHub*
* MPCNN sentence similarity tensorflow [[link]](https://github.com/lc222/MPCNN-sentence-similarity-tensorflow) *GitHub*
* Siamese Recurrent Architectures for Learning Sentence Similarity [[download]](https://www.aaai.org/ocs/index.php/AAAI/AAAI16/paper/download/12195/12023) *pdf*
* deep siamese text similarity [[link]](https://github.com/dhwajraj/deep-siamese-text-similarity) *GitHub*
* 딥러닝 기반 자연어처리 기법의 최근 연구 동향 [[link]](https://ratsgo.github.io/natural%20language%20processing/2017/08/16/deepNLP/) *blog*
* NLP, ratsgo's blog [[link]](https://ratsgo.github.io/blog/categories/#natural-language-processing) *blog* 💯👍🌟

**Comment by GzuPark** [comment]
### docker youtube
1. sktechx docker [[link]](https://www.youtube.com/watch?v=o4_KESBNFhI), [[준비 문서]](https://gist.github.com/nacyot/ed3b5a4e8137e9873d17942f0640c471)

**Comment by ChoiKW** [comment]
docker for windows 10 home [[가이드]](https://gwonsungjun.github.io/how%20to%20install/2018/01/28/DockerInstall/)

**Comment by GzuPark** [comment]
### 오늘코드 튜토리얼 docker image
1. 로컬컴퓨터 내에 docker image와 공유할 디렉토리 생성 (예: `/Users/jijupax/data`, **<공유경로>** 로 표시)
2. **<공유경로>** 안에서 `git clone https://github.com/corazzon/KaggleStruggle.git` 실행
3. `docker pull hermits/korean-nlp:1.0`
4. `docker run  -p 8888:8888 -p 6006:6006 -v <공유경로>:/notebooks -it hermits/korean-nlp:1.0 bash`
5. docker 실행 후, `ls` 명령어를 통해 `KaggleStruggle` 폴더가 보이면 성공
6. `jupyter notebook --allow-root --NotebookApp.token=''`, Ipython notebook 실행시키는 명령어
7. 인터넷 브라우저에서 `localhost:8888` 입력하고, `KaggleStruggle` 폴더가 보이면 성공

##### 재실행
1. `docker ps -a` 를 실행해서 컨테이너 id 를 기억, id는 고유한 4~5자리 정도까지만 기억하고 입력하면됨
2. `docker restart <컨테이너ID>` 입력
2-1. 만약 오류가 생긴다면, docker gui에서 settings > reset > restart docker 실행 [[참고]](https://github.com/docker/for-win/issues/1038#issue-252808769)
3. `docker attach <컨테이너ID>`
